#!/bin/sh
# Rename file in UTF-8
TIME="$(date -u --iso=sec)"
if [ "$NAUTILUS_SCRIPT_CURRENT_URI" != "${NAUTILUS_SCRIPT_CURRENT_URI#file://}" ]; then
  echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | {
    while true; do
      read FILE_UTF8
      if [ -z "$FILE_UTF8" ]; then
        break
      fi
      FILE_SJIS="$(echo "$FILE_UTF8" | iconv -t sjis -f utf-8)"
      if [ "$FILE_UTF8" != "$FILE_SJIS" ]; then
        if [ -e "$FILE_SJIS" ]; then
          # if pre-exists, backup
          mv -f "$FILE_SJIS" "${FILE_SJIS}.$TIME.orig"
        fi
        mv "$FILE_UTF8" "$FILE_SJIS"
      fi
    done
  }
fi
